### ISSUE TITLE
Nenio fails to mount

### ISSUE THREAD

**Issue by Bluejay47** [DarthParametric/AutoMount_for_TabletopTweaks#1] opened 2024-12-07 05:32 UTC
If Nenio has an animal companion (through respecing for example), automount will fail for her when she is in human form because she is poly-morphed. Probably not intended?
![Nenio](https://github.com/user-attachments/assets/bd7c2ff9-08a3-47fd-8229-5fa8b78bb9e3)

**Comment by DarthParametric** [comment] 2024-12-11 07:04
That is the intended behaviour for regular characters (so you can't ride a horse while polymorphed into a dragon, for example), but I didn't account for Nenio being considered as polymorphed normally. I'll have to add an exception for her. Thanks for the heads-up.

**Comment by DarthParametric** [comment] 2024-12-11 10:06
Should be fixed by [v1.2.2](https://github.com/DarthParametric/AutoMount_for_TabletopTweaks/releases/latest).

**Closed as completed by DarthParametric** 2024-12-11 10:06 UTC
